<a href="https://colab.research.google.com/github/guilhermebr84/XPE_bootcamp_kmeans_analistadedados/blob/main/kmeans_iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 01 - importar bibliotecas

In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

# 02 - verificar versoes das bibliotecas

In [ ]:
import sklearn
import plotly

print(f'''verificando as versoes de bibliotecas:\n
pandas: {pd.__version__}
numpy: {np.__version__}
sklearn: {sklearn.__version__}
plotly: {plotly.__version__}
''')

verificando as versoes de bibliotecas:

pandas: 1.5.3
numpy: 1.22.4
sklearn: 1.2.2
plotly: 5.13.1



# 03 - coletar dados

In [ ]:
iris = pd.read_csv('/content/iris.csv', sep=';')

# 04 - analisar dados

In [ ]:
iris.head()

sepal length  sepal width  petal length  petal width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
iris.tail()

sepal length  sepal width  petal length  petal width           Class
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [ ]:
# gerar estatisticas com a base de dados
iris.describe()

sepal length  sepal width  petal length  petal width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [ ]:
# n. de classes existentes no dataframe
iris['Class'].unique() # cria uma array indicando os valores existentes de uma das colunas

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [ ]:
# contar n. de classes
len(iris['Class'].unique()) #quantifica as classes

3

In [ ]:
# avaliar numero de linhas e colunas do dataset
iris.shape #quero saber, respec
# output: 150 linhas e 5 colunas

(150, 5)

In [ ]:
# verificar valores nulos / ausentes 01
iris.isna()

sepal length  sepal width  petal length  petal width  Class
0           False        False         False        False  False
1           False        False         False        False  False
2           False        False         False        False  False
3           False        False         False        False  False
4           False        False         False        False  False
..            ...          ...           ...          ...    ...
145         False        False         False        False  False
146         False        False         False        False  False
147         False        False         False        False  False
148         False        False         False        False  False
149         False        False         False        False  False

[150 rows x 5 columns]

In [ ]:
# verificar valores nulos / ausentes 02
iris.isna().sum()
# output = não há valores nulos / ausentes

sepal length    0
sepal width     0
petal length    0
petal width     0
Class           0
dtype: int64

In [ ]:
# verificar informacoes coletadas
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal length  150 non-null    float64
 1   sepal width   150 non-null    float64
 2   petal length  150 non-null    float64
 3   petal width   150 non-null    float64
 4   Class         150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


# Criando clusters
agrupar dados baseados no comprimento e largura das petalas

In [ ]:
# coletar os dados das petalas
iris.head()

sepal length  sepal width  petal length  petal width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
# criar variavel X com as colunas petal length e petal width
X_petala = iris.iloc[:,[2,3]].values #determinando uma variável para a array das petalas
X_petala[:10] #chamando somente os 10 primeiros

array([[1.4, 0.2],
       [1.4, 0.2],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.7, 0.4],
       [1.4, 0.3],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.5, 0.1]])

# Normalização de Dados
Dados em escalas diferentes - normaliza-se os dados num mesmo padrão e escala

O KMeans realiza os cálculos baseado na distância, entao devemos normalizar/padronizar para não destoar um atributo do outro.

O algoritmo pode ser tendecioso se não normalizar.

In [ ]:
# para esse experimento vamos utilizar o Zscore - converte todos os valores em uma pontuação Z
normalizar_dados = StandardScaler()
X_petala = normalizar_dados.fit_transform(X_petala) 
X_petala[:10]

array([[-1.3412724 , -1.31297673],
       [-1.3412724 , -1.31297673],
       [-1.39813811, -1.31297673],
       [-1.2844067 , -1.31297673],
       [-1.3412724 , -1.31297673],
       [-1.17067529, -1.05003079],
       [-1.3412724 , -1.18150376],
       [-1.2844067 , -1.31297673],
       [-1.3412724 , -1.31297673],
       [-1.2844067 , -1.4444497 ]])

In [ ]:
# calcular numero de clusters
wcss_petala = []
for i in range(1,11):
  kmeans_petala = KMeans(n_clusters=i, random_state=0)
  kmeans_petala.fit(X_petala)
  wcss_petala.append(kmeans_petala.inertia_)

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:8

In [ ]:
# visualizar valores de wcss
for i in range (len(wcss_petala)):
  print('Cluster:', i, 'valor do WCSS: ', wcss_petala[i])

Cluster: 0 valor do WCSS:  300.0000000000001
Cluster: 1 valor do WCSS:  54.14584701344988
Cluster: 2 valor do WCSS:  18.046983891906276
Cluster: 3 valor do WCSS:  12.307440251261843
Cluster: 4 valor do WCSS:  9.181131495513899
Cluster: 5 valor do WCSS:  7.215096212730807
Cluster: 6 valor do WCSS:  6.026593155951448
Cluster: 7 valor do WCSS:  5.173315218915379
Cluster: 8 valor do WCSS:  4.419290104197288
Cluster: 9 valor do WCSS:  3.9139417830543204


In [ ]:
#definindo melhor clusters para as petalas
grafico_cotovelo_petala = px.line(x=range(1,11), y=wcss_petala)
grafico_cotovelo_petala.show()

In [ ]:
# melhorando o grafico
grafico_cotovelo_petala = px.line(x=range(1,11), y=wcss_petala)
grafico_cotovelo_petala.update_xaxes(title_text='Número de Clusters')
grafico_cotovelo_petala.update_yaxes(title_text='Valor de WCSS')
grafico_cotovelo_petala.update_layout(title_text='Definindo o número de Clusters', title_x=0.5)
grafico_cotovelo_petala.show()

In [ ]:
#executar o kmeans para as petalas
kmeans_petala = KMeans(n_clusters=3, random_state=0)
label_cluster_petala = kmeans_petala.fit_predict(X_petala)

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning:

The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning



In [ ]:
#verifica a classificação dos clusters
label_cluster_petala

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [ ]:
#visualizando o centroides de cada cluster
centroides_petala = kmeans_petala.cluster_centers_
centroides_petala

array([[-1.30487835, -1.25512862],
       [ 1.02813193,  1.12749028],
       [ 0.30564587,  0.16609419]])

In [ ]:
# visualizando dados agrupados com dados das petalas
grafico_petala = px.scatter(x = X_petala[:,0], y = X_petala[:,1], color = label_cluster_petala)
grafico_centroide_petala = px.scatter(x = centroides_petala[:,0], y = centroides_petala[:,1], size=[7,7,7])
grafico_final = go.Figure(data=grafico_petala.data + grafico_centroide_petala.data)
grafico_final.show()

In [ ]:
centroides_petala

array([[-1.30487835, -1.25512862],
       [ 1.02813193,  1.12749028],
       [ 0.30564587,  0.16609419]])

#Criando os clusters para sepalas
realizar o agrupamento baseado no comprimento e largura das sepalas

In [ ]:
iris.head()

sepal length  sepal width  petal length  petal width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
#coletando dados das sepalas
#agrupando sepalas
X_sepala = iris.iloc[:,[0,1]].values
X_sepala = normalizar_dados.fit_transform(X_sepala)
X_sepala[:5]

array([[-0.90068117,  1.03205722],
       [-1.14301691, -0.1249576 ],
       [-1.38535265,  0.33784833],
       [-1.50652052,  0.10644536],
       [-1.02184904,  1.26346019]])

#calcular valor wcss

In [ ]:
wcss_sepala = []
for i in range(1,11):
  kmeans_sepala = KMeans(n_clusters=i, random_state=0)
  kmeans_sepala.fit(X_sepala)
  wcss_sepala.append(kmeans_sepala.inertia_)

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning:

The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning:

The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning:

The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning:

The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning:

The default value of `n_init` will chang

In [ ]:
#visualizar grafico
grafico_cotovelo_sepala = px.line(x=range(1,11), y=wcss_sepala)
grafico_cotovelo_sepala.update_xaxes(title_text='Número de Clusters')
grafico_cotovelo_sepala.update_yaxes(title_text='Valor de WCSS')
grafico_cotovelo_sepala.update_layout(title_text='Definindo o número de Clusters', title_x=0.5)
grafico_cotovelo_sepala.show()

In [ ]:
#definindo melhor o numero de clusters das sépalas
kmeans_sepala = KMeans(n_clusters=3, random_state=0)
label_cluster_sepala = kmeans_sepala.fit_predict(X_sepala)

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning:

The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning



In [ ]:
kmeans_sepala

KMeans(n_clusters=3, random_state=0)

In [ ]:
#verificar a classificacao dos clusters

In [ ]:
#visualizar dados agrupados com dados de sépalas
centroides_sepala = kmeans_sepala.cluster_centers_
centroides_sepala

array([[-0.04825457, -0.89224112],
       [-0.97822861,  0.89321545],
       [ 1.20144049,  0.14411561]])

In [ ]:
grafico_sepala = px.scatter(x = X_sepala[:,0], y = X_sepala[:,1], color = label_cluster_sepala)
grafico_centroide_sepala = px.scatter(x = centroides_sepala[:,0], y = centroides_sepala[:,1], size=[7,7,7])
grafico_final2 = go.Figure(data=grafico_sepala.data + grafico_centroide_sepala.data)
grafico_final2.show()

In [ ]:
#criando funcao
def gera_grafico(x,y,color,X_centroide, Y_centroide)

grafico_sepala = px.scatter(x = X_sepala[:,0], y = X_sepala[:,1], color = label_cluster_sepala)
grafico_centroide_sepala = px.scatter(x = centroides_sepala[:,0], y = centroides_sepala[:,1], size=[7,7,7])
grafico_final2 = go.Figure(data=grafico_sepala.data + grafico_centroide_sepala.data)
grafico_final2.show()